<h1>Welcome to Lynx</h1>

<p>Lynx is a personal bookmarking tool that allows to to bookmark websites and have those bookmarks available to you from any computer.</p>

<p>Lynx is integrated into the main website and other platforms allowing you to easily bookmark new pages as well as browse your bookmarks. Look for 'bookmark this page' links on the site.</p>

<h2>Getting Started</h2>

<ul>
	<li>Click on the "<a href="<?php echo $this->url(array(), 'user'); ?>">My Lynx</a>" menu above to browse you list of bookmarks</li>
	<li>Click on the "<a href="<?php echo $this->url(array(), 'user_create'); ?>">New Bookmark</a>" menu above to add a new bookmark for any web address.</li>
	<li>Clock on the "<a href="<?php echo $this->url(array(), 'public'); ?>">Public Lynx</a>" menu above to browse the pages that others in the community have bookmarked.</li>
</ul>