<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    
    <?php echo $this->headLink() ?>
    
    <?php echo $this->headStyle() ?>
    
    <?php echo $this->headScript() ?>
    
</head>
<body>
	<div class="main">
		<div class="header">
			<div class="headerWelcome">
				Welcome USERNAME &#160; | &#160;
				<a href="#">Logout</a> &#160; | &#160;
				<a href="#" onclick="setActiveStyleSheet('fixed'); return false;">Fixed</a> or
				<a href="#" onclick="setActiveStyleSheet('flex'); return false;">Flex</a>
			</div>
			<div class="clear">&#160;</div>
			<a href="http://www.middlebury.edu">
				<img class="headerLogo" src="https://web.middlebury.edu/development/tools/2d/Images/mclogo.gif" alt="Click here to return to Middlebury College home page" />
			</a>
			<div class="headerSite">
				<h1><?php echo $this->title(); ?></h1>
			</div>
			<div class="clear">
				&#160;
			</div>
		</div>
		
		<div class="headerNavigation">
			<div class="CssMenu">
				<div class="AspNet-Menu-Horizontal">
					<?php // echo $this->placeholder('nav') ?>
				</div>
			</div>
			<div class="clear">&#160;</div>
		</div>
		<div class="content">
			<?php echo $this->layout()->content ?> 
		</div>
	</div>

</body>
</html>