<?php

print $this->paginationControl($this->paginator, 'Sliding', 'mark_pagination_control.phtml');

print "\n<ul class='bookmarks'>";
foreach ($this->paginator as $mark) {
	print "\n\t<li class='bookmark'>";
	print "\n\t\t<div class='data'>";
	
	print "\n\t\t\t<h4>";
	print "\n\t\t\t\t<a href=\"".$this->escape($mark->url)."\" target='_blank'>";
	print $this->escape($mark->description);
	print "</a>";
	print "\n\t\t\t</h4>";
	
	print "\n\t\t\t<div class='full_url'>";
	print "\n\t\t\t\t<a href=\"".$this->escape($mark->url)."\" target='_blank'>";
	print $this->escape($mark->url);
	print "</a>";
	print "\n\t\t\t</div>";
	
	print "\n\t\t\t<div class='notes'>";
	print nl2br($this->escape($mark->notes));
	print "\n\t\t\t</div>";
	
	print "\n\t\t\t<ul class='tags'>";
	foreach ($mark->tags as $tag) {
		print "\n\t\t\t\t<li class='tag'>";
		print "\n\t\t\t\t<a href=\"".$this->url(array('tag' => $tag, 'page' => null), 'user_tag')."\">";
		print $this->escape($tag);
		print "</a>";
		print "\n\t\t\t\t</li>";
	}
	print "\n\t\t\t</ul>";
	
	print "\n\t\t</div>";
	print "\n\t\t<div class='actions'>";
	print "\n\t\t\t<a href=\"".$this->url(array('mark' => $mark->id, 'page' => null), 'user_edit')."\">EDIT</a>";
	print "\n\t\t\t | ";
	print "\n\t\t\t<form action=\"".$this->url(array('page' => null), 'user_delete')."\" method='post' class='delete_form' onsubmit=\"if (confirm('Really Delete?')) { } else {return false;}\">";
	print "\n\t\t\t\t<input type='hidden' name='mark' value='".$mark->id."'/>";
	print "\n\t\t\t\t<input type='hidden' name='no_ajax' value='1'/>";
	print "\n\t\t\t\t<input type='submit' value='DELETE'/>";
	print "\n\t\t\t</form>";
	print "\n\t\t</div>";
	
	print "\n\t\t<div class='clr'></div>";
	print "\n\t</li>";
}
print "\n</ul>";

print $this->paginationControl($this->paginator, 'Sliding', 'mark_pagination_control.phtml');

