<?php
print "\n<posts";
if (isset($this->matches))
	print " matches='".$this->matches."'";
print ">";

foreach ($this->marks as $mark) {
	print "\n\t<post href=\"".$mark->url."\"
		description=\"".$this->escape($mark->description)."\"
		extended=\"".$this->escape(preg_replace("/\n|\r/", "", nl2br($mark->notes)))."\"
		hash=\"".md5($mark->url)."\"
		meta=\"".md5($mark->id.' '.$mark->updateTime)."\"
		others=\"".intval($mark->others)."\"
		tag=\"".implode(' ', $mark->tags)."\"
		time=\"".$mark->updateTime."\"
		/>";
}

?>
</posts>